baseURL = "http://andrew.cobaugh.io/"
languageCode = "en-us"
title = "Andrew Cobaugh"
theme = "gohugo-theme-ananke"

publishDir = "docs"

[params]
	favicon = ""
	description = ""

	background_color_class = "bg-black"
	featured_image = "/images/background.jpg"

	github = "https://github.com/acobaugh"
	instagram = "https://instagram.com/andrew.cobaugh"
	linkedin = "https://www.linkedin.com/in/andrew-cobaugh"
